---
title: "stl_lead_inequity"
format: html
editor: visual
execute: 
  echo: true
  warning: false
---

```{r}
library(tidyverse)
library(janitor)
library(here)
library(skimr)
library(dplyr)
```

```{r}
stl_lead <- read_csv(here::here("data", "stl_blood_lead.csv")) 

stl_lead <- stl_lead %>% clean_names()

```

```{r}
stl_lead_prop <- stl_lead %>% dplyr::mutate(prop_white = white / total_pop * 100) 

stl_lead_prop

```

```{r}
stl_lead_plot <- ggplot(data = stl_lead_prop,
                           aes(x = pct_elevated, y = prop_white)) + geom_point()

stl_lead_plot

ggsave(plot = stl_lead_plot, 
       here("figs", "stl_lead_plot.png"), 
            width = 6, height = 5, dpi = 200)

#In text above or below the scatterplot, write 1 - 2 sentences describing the overall trend that you observe from your graph
```

```{r}
pct_Elevated_plot <- ggplot(data = stl_lead_prop,  
                            aes(x = pct_elevated)) +  geom_histogram()

pct_Elevated_plot 

ggsave(plot = pct_Elevated_plot, 
       here("figs", "pct_elevated_plot.jpg"),
       width = 6, height = 5, dpi = 200)
```
